version: 2.1
orbs:
  node: circleci/node@1.1.6
workflows:
  CI:
    jobs:
      build:
        docker:
          - image: circleci/node:carbon
        steps:
          - checkout
          - node/with-cache:
              steps:
                - run: npm install
          - run: npm run test
