version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install
      - run:
          name: Run tests
          command: |
            mkdir -p ~/test-results/junit
            npm test --ci --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: ~/test-results/junit/results.xml
      - store_artifacts:
          path: ~/test-results/junit
      - store_test_results:
          path: ~/test-results
